# Copyright 2019, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: nodejs16
beta_settings:
  cloud_sql_instances: find-and-consult:asia-south1:fcweb
# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/find-and-consult:asia-south1:fcweb
  DB_USER: root
  DB_PASS: mV\S`5esU+^~^Mpt
  DB_NAME: web
  DB_HOST: 35.200.243.143
  NODE_ENV: PROD