
ALTER TABLE blogs   DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=3;


ALTER TABLE blog_categories   DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=5;

ALTER TABLE categories  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=8;


ALTER TABLE clients DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=14;

ALTER TABLE client_logs  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=12;

ALTER TABLE countries  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=7;

ALTER TABLE days  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=8;

ALTER TABLE failed_jobs  MODIFY id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE leads  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=2;

ALTER TABLE listings  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=40;

ALTER TABLE listing_categories  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=29;

ALTER TABLE listing_country_deals  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=26;

ALTER TABLE listing_images  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=51;

ALTER TABLE listing_opening_hours  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=26;

ALTER TABLE listing_reviews  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=6;

ALTER TABLE listing_services  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=12;

ALTER TABLE listing_service_details  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=20;

ALTER TABLE listing_social_links  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY;

ALTER TABLE listing_wishlists  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=3;

ALTER TABLE log_statuses  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=9;

ALTER TABLE migrations  MODIFY id int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

ALTER TABLE payments  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=3;

ALTER TABLE personal_access_tokens  MODIFY id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE plans  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=2;

ALTER TABLE ribbon_tags  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=4;

ALTER TABLE social_links  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=6;

ALTER TABLE users  MODIFY id bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=375;

ALTER TABLE user_otp  DROP COLUMN id, ADD COLUMN id INT PRIMARY KEY, AUTO_INCREMENT=83;
